### ISSUE TITLE
NCCL error  when train with single node & multi gpus

### ISSUE THREAD

**Issue by Oliver-ss** [LeeDoYup/FixMatch-pytorch#2]
Hi,
I tried to run the command
```
python train.py --world-size 1 --rank 0 --multiprocessing-distributed --num_labels 4000 --save_name cifar10_4000 --dataset cifar10 --num_classes 10
```
but the following exception was raised:
```
Traceback (most recent call last):
  File "train.py", line 316, in <module>
    main(args)
  File "train.py", line 62, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/home/yuansong/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/yuansong/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/yuansong/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/yuansong/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/data/FixMatch-pytorch/train.py", line 155, in main_worker
    device_ids=[args.gpu])
  File "/home/yuansong/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 333, in __init__
    self.broadcast_bucket_size)
  File "/home/yuansong/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 549, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:492, unhandled system error, NCCL version 2.4.8
```
I am not sure whether you met a similar problem before. If so, how did you solve it? Thanks!

**Comment by LeeDoYup** [comment]
Hello.
I think that the error is related to NCCL, not the implementation.

I recommend to try NCCL test in here: https://github.com/NVIDIA/nccl-tests

**Comment by LeeDoYup** [comment]
Inactivated issue, so i close it.

**Comment by LeeDoYup** [comment]
Also, it is not related to the implementation, but NCCL.
